<a href="https://colab.research.google.com/github/FranciniSantana/Data-Analysis-With-Python-FreeCodeCamp/blob/main/1_Data_Analysis_With_Python_freeCodeCamp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>




#Importando Bibliotecas de Trabalho




In [ ]:
import numpy as np

# Boolean Array

In [ ]:
a = np.arange(10) # cria um array unidimensional/vetor de 4 elementos de 0 a 3
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b = np.array([0,1,2])

In [ ]:
b

array([10, 10, 10])

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
a[0], a[1] # acessa um elemento do array pela sua posição/índice

(0, 1)

In [ ]:
a[[0,1]] # # acessa vários elementos do array pela sua posição/índice

array([0, 1])

In [ ]:
a[[True,False,False,True]] #acessas elementros através de uma lista ordenada e retorna os valores sendo eles verdadeiros


array([0, 3])

In [ ]:
a >= 2 # testa os elementos de um array retornando True or False para todos.

array([False, False,  True,  True])

In [ ]:
print(a[a>1]) #usei o print para entender como os dados seriam impressos na tela

[2 3]


In [ ]:
a[a>1] # uma forma de visualizar os dados enquanto programadora | usa como uma forma de filtro | Where

array([2, 3])

In [ ]:
a[a>a.mean()] # Retorne o valor de a onde o a é maior que a média dos elementos

array([2, 3])

In [ ]:

A = np.random.randint(100,size = (3,3)) # atribuíção

In [ ]:
A

array([[43, 95, 63],
       [64, 77, 58],
       [86, 89, 37]])

In [ ]:
print(A)

[[43 95 63]
 [64 77 58]
 [86 89 37]]


In [ ]:
A > 30

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
A[np.array([ # me retorna o valor de A onde o Array que eu defini são uma lista de arrays.
      [True,  False,  True],
       [ True,  False,  True],
       [ True,  False,  True]])]

array([43, 63, 64, 58, 86, 37])

In [ ]:
b = np.array([["Livia","Julia","Carla"], #np.array cria um array dentro da biblioteca numpy
         [25,17,35]])

In [ ]:
print(b)

[['Livia' 'Julia' 'Carla']
 ['25' '17' '35']]


In [ ]:
A = np.array(5)
A[A>3]

array([5])

# Linear Algebra

In [ ]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [ ]:
B = np.array([
    [6,5],
    [4,3],
    [2,1]
])

In [ ]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [ ]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [ ]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

# Size of objects in Memory

In [ ]:
# Um número interio e Python é > 24 bytes
import sys 

sys.getsizeof(1)

28

In [ ]:
sys.getsizeof(10**100)

72

In [ ]:
#numpy é muito menor
size_int = np.dtype(int).itemsize
size_float = np.dtype(float).itemsize
print(f'The size of int is {size_int}')
print(f'The size of float is {size_float}')
if size_int == size_float:
  print(f'The size of numbers type is the same')
else:
  print('The size of numbers type is different')


The size of int is 8
The size of float is 8
The size of numbers type is the same


 Listas are even larger ans performance is better


In [ ]:
L = list(range(1000))
a = np.arange(1000)


In [ ]:
%time np.sum(a**2)


CPU times: user 99 µs, sys: 0 ns, total: 99 µs
Wall time: 104 µs


332833500

In [ ]:
%time sum([x**2 for x in L])

CPU times: user 458 µs, sys: 0 ns, total: 458 µs
Wall time: 467 µs


332833500