<a href="https://colab.research.google.com/github/FranciniSantana/Data-Analysis-With-Python-FreeCodeCamp/blob/main/Basics_of_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# The Basics


In [4]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [13]:
b = np.array([[9.0,8.0,7.0], [6.0,5.0,4.0]], dtype = 'int16')
print(b)

[[9 8 7]
 [6 5 4]]


In [7]:
a * b

array([[ 9., 16., 21.],
       [ 6., 10., 12.]])

In [9]:
# Get Dimension and Shape

print(a.ndim) # uma dimensão com três elementos
print(a.shape)

1
(3,)


In [10]:
print(b.ndim) # duas dimensões com três elementos
print(b.shape) # 2 rows and 3 columns

2
(2, 3)


In [11]:
a.dtype

dtype('int64')

In [14]:
b.dtype

dtype('int16')

In [15]:
#get size 
b.itemsize

2

# Acessing / Changing specific elements, rows, columns, etc


In [16]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [17]:
# get a specific element [Row,Column]
a[1,5]

13

In [18]:
# get a specific row - 
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [19]:
# get a specif columns
a[:,2]

array([ 3, 10])

In [20]:
a[0,1:6:2] # linha de index 0, coluna de index 1 até index 6 pulando de 2 em 2

array([2, 4, 6])

In [21]:
a[1,5] = 20

In [22]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
