<a href="https://colab.research.google.com/github/FranciniSantana/Data-Analysis-With-Python-FreeCodeCamp/blob/main/Projeto_Mean_Variance_Standard_Deviation_Calculator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Create a function named calculate() in mean_var_std.py that uses Numpy to output the mean, variance, standard deviation, max, min, and sum of the rows, columns, and elements in a 3 x 3 matrix.

The input of the function should be a list containing 9 digits. The function should convert the list into a 3 x 3 Numpy array, and then return a dictionary containing the mean, variance, standard deviation, max, min, and sum along both axes and for the flattened matrix.


In [1]:
import numpy as np
import pandas as pd


In [2]:
x = np.random.randint(100,size = (3,3))


In [3]:
x[[0,1,2]] # diferente de acessar uma lista por elemento, aqui eu aceso a linha inteira através do index.

array([[37, 97, 81],
       [46, 10, 84],
       [99, 78, 94]])

In [4]:
def calculate():
  x = np.array(x)


💡 Ler esse material: https://pythonexamples.org/numpy-mean/

In [5]:
list = [0,1,2,3,4,5,6,7,8] # variável contendo uma lista com 9 elementos

In [11]:
arr = np.array(list)
arr = arr.reshape(3,3)

arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
array = []  # para criar um array usei o método append para separar os elementos da lista em 3 listas

array.append(list[0:3])
array.append(list[3:6])
array.append(list[6:9])


array

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

In [7]:
a = np.array(array) # para transformar as três listas em um array usei o método np.array()
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
from numpy.core.memmap import dtype
from numpy.core.fromnumeric import mean
mean_ = [a.mean(axis=0) , a.mean(axis = 1 ), a.mean()]
var_ = [a.var(axis=0) , a.var(axis = 1 ), a.var()]
std_ = [a.std(axis=0) , a.std(axis = 1 ), a.std()]
min_ = [a.min(axis=0) , a.min(axis = 1 ), a.min()]
max_ = [a.max(axis=0) , a.max(axis = 1 ), a.max()]




                                             
print(mean_)
print(var_)
print(std_)
print(min_)
print(max_)
#print(type(mean_)


[array([3., 4., 5.]), array([1., 4., 7.]), 4.0]
[array([6., 6., 6.]), array([0.66666667, 0.66666667, 0.66666667]), 6.666666666666667]
[array([2.44948974, 2.44948974, 2.44948974]), array([0.81649658, 0.81649658, 0.81649658]), 2.581988897471611]
[array([0, 1, 2]), array([0, 3, 6]), 0]
[array([6, 7, 8]), array([2, 5, 8]), 8]


In [9]:
teste = a.mean(axis=0)
type(teste)

numpy.ndarray

In [22]:
calculate([0,1,2,3,4,5,6,7,8])

<function __main__.calculate(list)>

In [25]:
def calculate(list):
  if len(list) != 9:
    raise ValueError("List must contain nine numbers.")
  else:
    arr = np.array(list)
    arr = arr.reshape(3, 3)
    mean = [np.mean(arr, axis=0).tolist(), np.mean(arr, axis=1).tolist(), np.mean(arr)]
    var = [np.var(arr, axis=0).tolist(), np.var(arr, axis=1).tolist(), np.var(arr)]
    std = [np.std(arr, axis=0).tolist(), np.std(arr, axis=1).tolist(), np.std(arr)]
    mx = [np.max(arr, axis=0).tolist(), np.max(arr, axis=1).tolist(), np.max(arr)]
    mn = [np.min(arr, axis=0).tolist(), np.min(arr, axis=1).tolist(), np.min(arr)]
    s = [np.sum(arr, axis=0).tolist(), np.sum(arr, axis=1).tolist(), np.sum(arr)]
  
    calculations = {
      'mean' : mean,
      'variance' : var,
      'standard deviation' : std,
      'max' : mx,
      'min' : mn,
      'sum' : s,
    }

    return calculations


In [26]:
b = [0,1,2,3,4,5,6,7,8]
calculate(b)

{'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0],
 'variance': [[6.0, 6.0, 6.0],
  [0.6666666666666666, 0.6666666666666666, 0.6666666666666666],
  6.666666666666667],
 'standard deviation': [[2.449489742783178,
   2.449489742783178,
   2.449489742783178],
  [0.816496580927726, 0.816496580927726, 0.816496580927726],
  2.581988897471611],
 'max': [[6, 7, 8], [2, 5, 8], 8],
 'min': [[0, 1, 2], [0, 3, 6], 0],
 'sum': [[9, 12, 15], [3, 12, 21], 36]}